### ISSUE TITLE
Enhancement > Homepage > Keep Nav. Bar Sticky 

### ISSUE THREAD

**Issue by Jennymontoya** [vigetlabs/EcoCart#52]
**Is your feature request related to a problem? Please describe.**
The navigation bar is inconsistently sticking. You have to first scroll down for it to appear, and then it doesn't go away. Once it does appear it throws off the centering of the intro text box.

**Describe the solution you'd like**
It would be better just to keep the navigation bar sticking at the top of the screen from the start, re-centering the text box around the new framing. 

**Describe alternatives you've considered**
It is okay to keep it the way it is, but I think people will be searching for it if it doesn't appear from the beginning. Keeping the Navigation bar consistent would better fit comps as well. 

**Additional context**

See below what the top of the site looks like prior to appearance of nav bar vs. once it appears. 

![No-nav](https://user-images.githubusercontent.com/66967309/88966391-3b3e4080-d27a-11ea-9b2c-3415368d32b9.png)

![Text Scroll](https://user-images.githubusercontent.com/66967309/88966399-3ed1c780-d27a-11ea-9dd0-69a079dcd218.png)

**Comment by willyd332** [comment]
Hey jenny, I am unable to recreate the issue you are talking about. I think it may be because the site you were looking at was already outdated. The hero modal no longer should have scroll bars at all.

Additionally, the nav is intentionally not sticky at the beginning and intentionally doesn't go away. The idea is to have a full screen intro, and then the nav appears when you get to the groceries (as the nav it utterly useless without groceries in the cart). I think you would be right on a normal site, but this is really a data visualization, not a "website with pages" so the nav should be a bit different in my opinion.
